# Generated by Django 2.2.6 on 2019-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaje', models.CharField(max_length=100)),
                ('new_name', models.CharField(max_length=20)),
            ],
        ),
    ]
